- name: -----create dir1 in /home-----
  file:
    path: /home/dir1
    state: directory
  tags: dir1
- name: -----create file1 in dir1-----
  file:
    path: /home/dir1/file1
    state: touch
  tags: dir1/file1
- name: -----create dir2 in /home-----
  file:
    path: /home/dir2
    state: directory
  tags: dir2
- name: -----create file2 in dir2-----
  file:
    path: /home/dir2/file2
    state: touch
  tags: dir2/file2
